# Generated by Django 3.2.3 on 2021-07-19 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=500, null=True)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=500, null=True)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=500, null=True)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Activity_Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Education', models.CharField(blank=True, max_length=50, null=True)),
                ('Sports', models.CharField(blank=True, max_length=50, null=True)),
                ('Level', models.CharField(blank=True, max_length=50, null=True)),
                ('Medal', models.CharField(blank=True, max_length=50, null=True)),
                ('Number_of_Medals', models.CharField(blank=True, max_length=50, null=True)),
                ('Certificate', models.FileField(blank=True, null=True, upload_to='Student_Certificate')),
                ('Performing_Arts', models.CharField(blank=True, max_length=50, null=True)),
                ('Performing_Arts_if_any', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
