# Generated by Django 3.2.3 on 2021-08-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Email', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_activity_email',
            name='Certificate',
            field=models.FileField(blank=True, default=1, upload_to='Student_Certificate'),
            preserve_default=False,
        ),
    ]
