# Generated by Django 3.2.3 on 2021-07-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='Member_documents'),
        ),
    ]
