# Generated by Django 3.2.3 on 2021-07-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0002_alter_member_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='Terms_and_Conditions',
            field=models.BooleanField(default=False),
        ),
    ]
