# Generated by Django 3.2.3 on 2021-08-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Member', '0003_member_terms_and_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_college_and_university',
            name='Profile_Picture',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to='CollegeProfile'),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='member_profile_picture'),
        ),
    ]
