# Generated by Django 3.2.3 on 2021-07-19 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Internship_Title', models.CharField(max_length=50)),
                ('Internship_Description', models.TextField()),
                ('Course', models.CharField(max_length=50)),
                ('Qualification', models.CharField(max_length=50)),
                ('Number_of_Openings', models.IntegerField()),
                ('Experience', models.IntegerField()),
                ('Salary', models.IntegerField()),
                ('Application_Process', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_Title', models.CharField(max_length=50)),
                ('Job_Description', models.TextField()),
                ('Course', models.CharField(max_length=50)),
                ('Qualification', models.CharField(max_length=50)),
                ('Number_of_Openings', models.IntegerField()),
                ('Experience', models.IntegerField()),
                ('Salary', models.IntegerField()),
                ('Application_Process', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orgnization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='New_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile', models.FileField(blank=True, default='download.jpg', null=True, upload_to='Company_Profile_Picture')),
                ('Company_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('Industry', models.CharField(blank=True, max_length=50, null=True)),
                ('Orgnization', models.CharField(blank=True, max_length=50, null=True)),
                ('Address_1', models.CharField(blank=True, max_length=500, null=True)),
                ('Address_2', models.CharField(blank=True, max_length=500, null=True)),
                ('City', models.CharField(blank=True, max_length=500, null=True)),
                ('State', models.CharField(blank=True, max_length=500, null=True)),
                ('Pin_Code', models.IntegerField(blank=True, null=True)),
                ('Country', models.CharField(blank=True, max_length=500, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
