# Generated by Django 3.2.3 on 2021-07-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_company',
            name='Profile',
            field=models.FileField(blank=True, default='download.jpg', null=True, upload_to='Company_profile'),
        ),
    ]
