# Generated by Django 3.2.3 on 2021-07-29 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_alter_new_company_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='Internship_Description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='internship',
            old_name='Internship_Title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Job_Description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='Job_Title',
            new_name='Title',
        ),
    ]
