# Generated by Django 3.2.3 on 2021-07-29 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0003_auto_20210729_1652'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Job',
            new_name='Internships',
        ),
        migrations.RenameModel(
            old_name='Internship',
            new_name='Jobs',
        ),
    ]
