# Generated by Django 3.2.3 on 2021-07-29 12:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Company', '0004_auto_20210729_1657'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='New_Company',
            new_name='company',
        ),
    ]
