# Generated by Django 3.2.3 on 2021-08-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0005_rename_new_company_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Terms_and_Conditions',
            field=models.BooleanField(default=False),
        ),
    ]
