# Generated by Django 3.2.3 on 2021-08-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0006_company_terms_and_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='Mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
