# Generated by Django 3.2.3 on 2021-08-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0007_company_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Profile',
            field=models.FileField(blank=True, default='default.png', null=True, upload_to='Company_profile'),
        ),
    ]
