# Generated by Django 3.2.3 on 2021-07-19 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile', models.FileField(blank=True, default='download.jpg', null=True, upload_to='Student_Profile_Picture')),
                ('First_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Middle_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('Last_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Mobile', models.CharField(blank=True, max_length=14, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=10, null=True)),
                ('Facebook_Profile', models.CharField(blank=True, max_length=50, null=True)),
                ('Linkedin', models.CharField(blank=True, max_length=50, null=True)),
                ('Twitter_Profile', models.CharField(blank=True, max_length=50, null=True)),
                ('Address_1', models.CharField(blank=True, max_length=200, null=True)),
                ('Address_2', models.CharField(blank=True, max_length=200, null=True)),
                ('City', models.CharField(blank=True, max_length=20, null=True)),
                ('State', models.CharField(blank=True, max_length=20, null=True)),
                ('Pin_Code', models.IntegerField(blank=True, null=True)),
                ('Country', models.CharField(blank=True, max_length=20, null=True)),
                ('Course', models.CharField(blank=True, max_length=50, null=True)),
                ('University_Name', models.CharField(blank=True, max_length=20, null=True)),
                ('Year_Start', models.DateField(blank=True, null=True)),
                ('Year_End', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='New_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('File', models.FileField(upload_to='New_Student_csv')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('activated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
