# Generated by Django 3.2.3 on 2021-07-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_auto_20210730_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='University_Country',
            field=models.CharField(blank=True, default='India', max_length=20, null=True),
        ),
    ]
