# Generated by Django 3.2.3 on 2021-07-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_alter_student_university_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Previous_University_Name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
