# Generated by Django 3.2.3 on 2021-08-02 11:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Student', '0004_student_previous_university_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Enrolled_Student',
        ),
    ]
