# Generated by Django 3.2.3 on 2021-08-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_remove_enrolled_student_previous_university_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrolled_student',
            name='Terms_and_Conditions',
            field=models.BooleanField(default=False),
        ),
    ]
